name: Unit-tests

on:
  pull_request:
    branches:
      - 'master'

jobs:
  Unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java17
        uses: actions/setup-java@v1
        with: {java-version: 17}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit-tests
        run: ./gradlew testDebugUnitTest
